---
- hosts: jenkins-master
  become: true
  tasks:
    - name: Update package cache
      apt:
        name: '*'
        state: latest

    - name: add Jenkins key
      become_user: root
      apt_key:
        url: https://pkg.jenkins.io/debian-stable/jenkins.io-2023.key
        state: present

    - name: add Jenkins repository
      become_user: root
      apt_repository:
        repo: 'deb https://pkg.jenkins.io/debian-stable binary/'
        state: present

    - name: install Java 17 OpenJDK
      apt:
        name: openjdk-17-jre
        state: present

    - name: install Jenkins
      apt:
        name: jenkins
        state: present

    - name: start Jenkins service
      service:
        name: jenkins
        state: started

    - name: enable Jenkins to start at boot
      service:
        name: jenkins
        enabled: yes