---
- hosts: Jenkins-master
  become: true
  tasks:
  - name: add jenkins key
    yum_key:
      url : https://pkg.jenkins.io/redhat-stable/jenkins.io-2023.key
      state: present

  - name: add jenkins repo   
    yum_repository: 
    repo: 'deb https://pkg.jenkins.io/redhat-stable/jenkins.repo'
    state: present

  - name: install java
    yum: 
      name: java-17-openjdk
      state: present
  
  - name: install jenkins
    yum:
      name: jenkins
      state: present
  
  - name: start jenkins service
    service:
      name: jenkins
      state: started

  - name : enable jenkins to start at boot cache_valid_time
    service:
      name: jenkins
      enabled: yes