---
- hosts: Jenkins-master
  become: true
  tasks:
    - name: Update package cache
      yum:
        name: '*'
        state: latest

    - name: add Jenkins key
      become_user: root
      rpm_key:
        key: https://pkg.jenkins.io/redhat-stable/jenkins.io-2023.key
        state: present

    - name: add Jenkins yum_repository
      become_user: root
      get_url:
        url: https://pkg.jenkins.io/redhat-stable/jenkins.repo
        dest: /etc/yum.repos.d/jenkins.repo

    - name: install Java 17 OpenJDK
      yum:
        name: java-17
        state: present

    - name: install Jenkins
      yum:
        name: jenkins
        state: present

    - name: start Jenkins service
      service:
        name: jenkins
        state: started

    - name: enable Jenkins to start at boot
      service:
        name: jenkins
        enabled: yes